# Generated by Django 6.0.4 on 2026-04-17 14:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateField(default=django.utils.timezone.now)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_open', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('commission', models.DecimalField(decimal_places=2, help_text='Commission percentage (e.g., 10.00)', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inflows', to='api.cashregister')),
            ],
        ),
        migrations.CreateModel(
            name='Outflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outflows', to='api.cashregister')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performed_services', to='api.employee')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_services', to='api.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('cash_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_orders', to='api.cashregister')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_orders', to='api.serviceorderstatus')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to='api.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='service_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.serviceorder'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='api.cashregister')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='api.paymentmethod')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='api.serviceorder')),
            ],
        ),
        migrations.AddField(
            model_name='serviceorderstatus',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_order_statuses', to='api.tenant'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='api.tenant'),
        ),
        migrations.AddField(
            model_name='employee',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='api.tenant'),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='api.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='cashregister',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_registers', to='api.tenant'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('license_plate', models.CharField(max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='api.client')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='api.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_orders', to='api.vehicle'),
        ),
        migrations.AddConstraint(
            model_name='serviceorderstatus',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_service_order_status_tenant'),
        ),
        migrations.AddConstraint(
            model_name='paymentmethod',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_payment_method_tenant'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('tenant', 'name', 'phone'), name='unique_employee_name_phone_tenant'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('tenant', 'name', 'phone'), name='unique_client_name_phone_tenant'),
        ),
        migrations.AddConstraint(
            model_name='cashregister',
            constraint=models.UniqueConstraint(fields=('tenant', 'register_date'), name='unique_cash_register_date_tenant'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('client', 'model_name'), name='unique_client_vehicle_model'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('tenant', 'license_plate'), name='unique_vehicle_plate_tenant'),
        ),
    ]
